version: '3'

services:
  postgre:
    container_name: postgre_db
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${POSTGRE_PORTS}
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
  redis:
    container_name: redis_store
    image: 'redis:alpine'
    restart: unless-stopped
    ports:
      - ${REDIS_PORT_DOCKER}
    env_file:
      - .env

  redis-commander:
    container_name: redis_gui
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=${REDIS_HOSTS}
    ports:
      - '8081:8081'
    depends_on:
      - redis
