version: '3'

services:
  postgre:
    container_name: postgre_db
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${DB_PORT}
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
  redis:
    container_name: redis_store
    image: 'redis:alpine'
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}
    env_file:
      - .env

  redis-commander:
    container_name: redis_gui
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=${REDIS_HOST}
    ports:
      - '8081:8081'
    depends_on:
      - redis
